apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: backend-image
        ports:
        - containerPort: 3000
